CREATE TABLE IF NOT EXISTS `#__djc2_checkout_log` (
    `id`              INT UNSIGNED      NOT NULL AUTO_INCREMENT,
    `event_type`      VARCHAR(50)       NOT NULL DEFAULT '',
    `session_id`      VARCHAR(191)      NOT NULL DEFAULT '',
    `user_id`         INT UNSIGNED      NOT NULL DEFAULT 0,
    `postcode`        VARCHAR(20)       NOT NULL DEFAULT '',
    `distance_km`     DECIMAL(8,2)               DEFAULT NULL,
    `distance_text`   VARCHAR(50)       NOT NULL DEFAULT '',
    `duration_text`   VARCHAR(100)      NOT NULL DEFAULT '',
    `delivery_options_json` TEXT                  DEFAULT NULL,
    `delivery_method` VARCHAR(255)      NOT NULL DEFAULT '',
    `delivery_id`     INT UNSIGNED      NOT NULL DEFAULT 0,
    `products_total`  DECIMAL(15,4)     NOT NULL DEFAULT '0.0000',
    `delivery_cost`   DECIMAL(15,4)     NOT NULL DEFAULT '0.0000',
    `payment_cost`    DECIMAL(15,4)     NOT NULL DEFAULT '0.0000',
    `grand_total`     DECIMAL(15,4)     NOT NULL DEFAULT '0.0000',
    `currency`        VARCHAR(10)       NOT NULL DEFAULT '',
    `order_id`        INT UNSIGNED      NOT NULL DEFAULT 0,
    `order_number`    VARCHAR(100)      NOT NULL DEFAULT '',
    `ip_address`      VARCHAR(45)       NOT NULL DEFAULT '',
    `created_at`      DATETIME          NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `idx_event_type`  (`event_type`),
    INDEX `idx_session_id`  (`session_id`),
    INDEX `idx_postcode`    (`postcode`),
    INDEX `idx_order_id`    (`order_id`),
    INDEX `idx_created_at`  (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
